# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_remove_user_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
