# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-20 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_auto_20181120_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyorder',
            name='librarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_orders', to='administrator.Administrator'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='administrator.Administrator'),
        ),
    ]
