# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_allbook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyorder',
            name='num',
            field=models.FloatField(),
        ),
    ]
