# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0005_auto_20181116_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_location', models.CharField(max_length=20, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_type', models.CharField(max_length=50, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
